version: "3.8"
services: 
  backend:
    container_name: backend-container
    restart: always
    build: ./backend
    ports: 
      - "8080:8080"
  
  frontend:
    container_name: frontend-container
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on: 
      - "backend"

# MANUAL
# sudo docker-compose build (build images)
# sudo docker-compose up -d (start containers)
# sudo docker-compose down  (delete containers)
