version: "3.8"
services: 
  backend:
    container_name: backend-container
    restart: always
    build: ./backend
    ports: 
      - "3001:80"
  
  frontend:
    container_name: frontend-container
    restart: always
    build: ./frontend
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./caddy-data:/data"
        #depends_on: 
        #- "backend"
        #stdin_open: true # docker run -i
        #tty: true        # docker run -t

# MANUAL
# sudo docker-compose build (build images)
# sudo docker-compose up -d (start containers)
# sudo docker-compose down  (delete containers)
