name: Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1.1.4
      with:
        version: 1.1.5
        virtualenvs-create: false
        virtualenvs-in-project: false
    - name: Install dependencies
      run: poetry install --no-root
      working-directory: backend
