name: Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1.1.4
      with:
        version: 1.1.5
        virtualenvs-create: false
        virtualenvs-in-project: false
    - name: Install dependencies
      run: poetry install --no-root
      working-directory: backend
    - name: Run Pylint
      run: pylint --fail_under=8.0 backend/app/*
    - name: Run Black
      run: black backend/app/*
    - name: Testing (PyTest)
      run: python -m pytest
      working-directory: backend
      
