name: Black

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install fastApi
    - name: Analysing the code with Black
      run: |
        black `ls -R|grep .py$|xargs`
